### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by horobetsb** [FrostAndrew/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by FrostAndrew** [comment]
Андрій Воробйов

**Comment by horobetsb** [comment]
Андрій Воробйов
Займаюся програмуванням в перервах між прокрастинацією і читанням. Хочу займатись прокрастинацією в перервах між програмуванням.
